language: cpp

dist: trusty
sudo: required
group: edge

compiler:
  - gcc

matrix:
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-9
      - CC=/usr/bin/gcc-9
      - CXX=/usr/bin/g++-9
      - CXXFLAGS=-std=c++2a -fconcepts
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9', 'libsdl2-2.0-0', 'libsdl2-image-2.0-0', 'libsdl2-dev', 'libsdl2-image-dev', 'libgtest-dev']

install:
  - make deps
  - cd /usr/src/googletest/googletest
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo cp libgtest* /usr/lib/
  - cd ..
  - sudo rm -rf build
  - sudo mkdir /usr/local/lib/googletest
  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/googletest/libgtest.a
  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/googletest/libgtest_main.a

script:
  - make build
  - make test
